### ISSUE TITLE
How to open/use it

### ISSUE THREAD

**Issue by Trusthoodies** [thisisnzed/Pandora#9]
Hello, how can i open and use the Pandora program?

**Comment by PandoricGalaxy** [comment]
> Hello, how can i open and use the Pandora program?

thats the issue rn... many of us dont know how to and the repo owner wont help!.. well he did write that he wont help for compilation in the readme but only after we asked. Youll have to find a way online to compile this and if u succeed, pls share it here

**Comment by kelnika** [comment]
this project sucks tho.Don't mind to compile it it's detected by many antiviruses.

**Comment by PandoricGalaxy** [comment]
> this project sucks tho.Don't mind to compile it it's detected by many antiviruses.

Detection is not the problem. That's something you have to do. But if you're saying so that means you compiled it, so how did you do it? Can you pls help?

**Comment by thisisnzed** [comment]
First of all, as I’ve always said, this project is only for the purpose of SHARING code, not to do tutorials on how to use Github; there are many tutorials on the internet.

> this project sucks tho.Don't mind to compile it it's detected by many antiviruses.

Then, the virus is now public, so it is obvious that antivirus detects it more and more easily.
However, in order to remove detections, you can follow this pattern:
* Compile in jar -> Obfuscate with a private obfuscator containing private transformers (e.g.: string obfuscator, number obfuscator, local polymorph, class folder, trimmer, shuffle members and more) -> Convert this .jar in .exe with tools such as Launch4j

**Comment by PandoricGalaxy** [comment]
Thanks I didn't know about converting .jar to .exe now I'll use it finnaly!!

**Comment by PandoricGalaxy** [comment]
>  Compile in jar -> Obfuscate with a private obfuscator containing private transformers (e.g.: string obfuscator, number obfuscator, local polymorph, class folder, trimmer, shuffle members and more) -> Convert this .jar in .exe with tools such as Launch4j

Have to convert master-snapshot.jar to exe right?

**Comment by PandoricGalaxy** [comment]
> this project sucks tho.Don't mind to compile it it's detected by many antiviruses.

Pls tell how did your compile the master and run it? Some people here not able to do it including me so pls help!

**Comment by thisisnzed** [comment]
There is no need to convert the master to exe

**Comment by PandoricGalaxy** [comment]
> There is no need to convert the master to exe

then what to do of master snapshot. i did java -jar master-1.0-SNAPSHOT.jar but it gave this:
![image](https://user-images.githubusercontent.com/86944806/164036926-28de9380-6697-410a-93c1-fbcdd903f19a.png)
